/**
 * mshop.discounts.api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DiscountType = 0 | 1;

export const DiscountType = {
    NUMBER_0: 0 as DiscountType,
    NUMBER_1: 1 as DiscountType
};

