/**
 * mshop.orders.api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderDto { 
    id?: string | null;
    clientEmail?: string | null;
    idProducts?: Array<string> | null;
    totalPriceBeforeDiscount?: number | null;
    totalPriceAfterDiscount?: number | null;
    discountPercentage?: number | null;
}

